[package]
name = "crsh-tx"
version = "0.2.0"
license = "MIT"
edition = "2024"

[dependencies]
crsh-core = { path = "../crsh-core" }
rustyline = "17.0.2"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
